---
title: "Test Website"
author: "Erika Gavenus"
date: "May 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries and Dataframe
```{r libraries}
suppressPackageStartupMessages({
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
})

```

```{r data}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1", method = "libcurl"), 
                stringsAsFactors = FALSE)
```

# Calculating Median Escapement

```{r median.calc}
median_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, SASAP.Region, Year, Location) %>% 
  summarize(escapement = sum(DailyCount, na.rm = T)) %>% 
  group_by(Species) %>% 
  summarize(median_escapement = median(escapement))

head(median_esc)
```

# Plot of Escapement by Species
### Median
```{r plot.median}
ggplot(median_esc, aes(x=Species, y=median_escapement)) +
  geom_col() +
  coord_flip()

```

```{r median.locations}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

datatable(locations)
```

# Map of Locations

```{r leaflet.map}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng=~Longitude, lat=~Latitude, popup = ~Location)
```

fixing problem of locations in Russia
```{r location.fix}
locs <- locations %>% 
  mutate(Longitude = abs(Longitude) * -1)

leaflet(locs) %>% 
  addTiles() %>% 
  addMarkers(lng=~Longitude, lat=~Latitude, popup = ~Location)

```

work-around for custom icon to appear in github
```{r}
# Use a custom marker so Leaflet doesn't try to grab the marker images from 
# its CDN (this was brought up in 
# https://github.com/NCEAS/sasap-training/issues/22)
markerIcon <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-icon.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41,
  shadowUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-shadow.png",
  shadowWidth = 41, shadowHeight = 41,
  shadowAnchorX = 13, shadowAnchorY = 41)
```

```{r final.map}
leaflet(locs) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location, icon = markerIcon)
```

